// r3tro skill test question bank: Linux command line
// Format: each question has a level (junior, mid or senior), the question text,
// optional code shown in a box, the answer options, the index of the correct
// option, and a short explanation. Options are shuffled when the test runs,
// so the correct answer can sit anywhere in the list.

window.R3TRO_BANKS = window.R3TRO_BANKS || {};
window.R3TRO_BANKS.linux = {
  title: 'Linux command line',
  short: 'Linux',
  blurb: 'Ten questions against the clock. Could you pass a real sysadmin interview?',
  questions: [
    // ---------- Junior ----------
    { level: 'junior', q: 'Which command prints the directory you are currently in?',
      options: ['pwd', 'cwd', 'dir --here', 'whereami'], answer: 0,
      explain: 'pwd stands for "print working directory". cwd and whereami are not standard commands.' },
    { level: 'junior', q: 'What does this show that plain ls does not?', code: 'ls -la',
      options: ['Hidden files, plus permissions, owner, size and dates', 'Only directories', 'Files sorted by size', 'Files in every subdirectory'], answer: 0,
      explain: '-l gives the long listing (permissions, owner, group, size, date) and -a includes hidden dotfiles.' },
    { level: 'junior', q: 'What permissions does this give the file?', code: 'chmod 755 deploy.sh',
      options: ['Owner can read, write, execute. Group and others can read and execute', 'Everyone can read, write and execute', 'Only the owner can read it', 'Owner can read and write. Nobody can execute'], answer: 0,
      explain: '7 = rwx for the owner, 5 = r-x for group and 5 = r-x for others, giving rwxr-xr-x.' },
    { level: 'junior', q: 'How do you show the last 20 lines of a log file?',
      options: ['tail -n 20 app.log', 'head -n 20 app.log', 'cat -20 app.log', 'less --last 20 app.log'], answer: 0,
      explain: 'tail shows the end of a file and -n sets how many lines. head shows the start.' },
    { level: 'junior', q: 'Which command lets you watch new lines appear in a log file as they are written?',
      options: ['tail -f app.log', 'cat -live app.log', 'head -f app.log', 'watch app.log'], answer: 0,
      explain: 'tail -f follows the file and prints new lines as they arrive. Press Ctrl+C to stop.' },
    { level: 'junior', q: 'What does this command do?', code: 'grep -i error app.log',
      options: ['Shows lines containing "error" in any upper or lower case', 'Counts the number of errors', 'Deletes lines containing "error"', 'Shows lines that do not contain "error"'], answer: 0,
      explain: '-i makes the match case-insensitive, so ERROR, Error and error all match. -v would invert the match.' },
    { level: 'junior', q: 'In a shell path, what does ~ refer to?',
      options: ['The current user\'s home directory', 'The root directory /', 'The previous directory', 'The /tmp directory'], answer: 0,
      explain: '~ expands to your home directory, for example /home/alice. cd - takes you to the previous directory.' },
    { level: 'junior', q: 'Which command copies a directory and everything inside it?',
      options: ['cp -r configs/ backup/', 'cp -d configs/ backup/', 'mv -c configs/ backup/', 'copy -a configs/ backup/'], answer: 0,
      explain: '-r (recursive) copies the directory and its contents. cp -a also works and preserves permissions and timestamps.' },
    { level: 'junior', q: 'What is the difference between these two?', code: 'echo "hi" > notes.txt\necho "hi" >> notes.txt',
      options: ['> overwrites the file, >> appends to the end', '> appends, >> overwrites', 'Both overwrite the file', '>> redirects errors only'], answer: 0,
      explain: 'A single > replaces the file contents. A double >> adds to the end, which is what you want for logs.' },
    { level: 'junior', q: 'What does sudo do?',
      options: ['Runs a command as another user, root by default', 'Switches the shell to a safe mode', 'Shows which user you are logged in as', 'Restarts the system safely'], answer: 0,
      explain: 'sudo runs a single command with another user\'s privileges, usually root, and logs who did it. whoami shows your user.' },
    { level: 'junior', q: 'Which command shows free space on each mounted filesystem?',
      options: ['df -h', 'du -h', 'free -h', 'lsblk'], answer: 0,
      explain: 'df reports filesystem usage. du measures directory sizes, free shows memory, and lsblk lists block devices.' },
    { level: 'junior', q: 'Which command shows how much RAM and swap are in use?',
      options: ['free -h', 'df -h', 'mem --show', 'top -m'], answer: 0,
      explain: 'free -h shows used and available memory and swap in human-readable units.' },
    { level: 'junior', q: 'What does the | (pipe) do in this command?', code: 'ps aux | grep nginx',
      options: ['Sends the output of the first command into the second', 'Runs both commands at the same time, unrelated', 'Runs grep only if ps fails', 'Saves the output to a file named grep'], answer: 0,
      explain: 'The pipe connects the standard output of ps to the standard input of grep.' },
    { level: 'junior', q: 'Which file lists the user accounts on a Linux system?',
      options: ['/etc/passwd', '/etc/users', '/var/accounts', '/etc/shadow-users'], answer: 0,
      explain: '/etc/passwd lists accounts. Password hashes live separately in /etc/shadow, which only root can read.' },
    { level: 'junior', q: 'Which command lists all running processes on the system?',
      options: ['ps aux', 'ls /proc --running', 'jobs', 'proc -a'], answer: 0,
      explain: 'ps aux lists every process with its user, CPU and memory use. jobs only shows jobs started from your current shell.' },
    { level: 'junior', q: 'How do you open the manual page for a command like rsync?',
      options: ['man rsync', 'help rsync', 'rsync --manual', 'info --page rsync'], answer: 0,
      explain: 'man opens the manual page. Many commands also support --help for a shorter summary.' },

    // ---------- Mid ----------
    { level: 'mid', q: 'Which command finds files larger than 100 MB under /var?',
      options: ['find /var -type f -size +100M', 'find /var -type f -size 100M', 'find /var -larger 100M', 'du /var --over 100M'], answer: 0,
      explain: 'The + means "greater than". Without it, -size 100M matches files of roughly exactly 100 MB.' },
    { level: 'mid', q: 'Which command shows which process is listening on port 443?',
      options: ['ss -tlnp | grep :443', 'netstat -r | grep 443', 'ps aux | grep 443', 'lsof -d 443'], answer: 0,
      explain: 'ss -tlnp lists TCP listening sockets with numeric ports and the owning process. netstat -r shows the routing table.' },
    { level: 'mid', q: 'How do you view the logs for the nginx systemd service?',
      options: ['journalctl -u nginx', 'journalctl -s nginx', 'systemctl logs nginx', 'tail /var/log/systemd/nginx'], answer: 0,
      explain: '-u filters the journal by unit. Add -f to follow live, or --since "1 hour ago" to narrow it down.' },
    { level: 'mid', q: 'How do you make a systemd service start automatically at boot?',
      options: ['systemctl enable nginx', 'systemctl start nginx', 'systemctl boot nginx', 'service nginx autostart'], answer: 0,
      explain: 'enable sets it to start at boot. start only runs it now. enable --now does both.' },
    { level: 'mid', q: 'What does this print?', code: 'some_command\necho $?',
      options: ['The exit code of the last command', 'The process ID of the last command', 'The number of arguments passed', 'The current shell\'s PID'], answer: 0,
      explain: '$? holds the last exit status. 0 means success, anything else means failure. $$ is the shell\'s PID.' },
    { level: 'mid', q: 'What signal does kill send by default?', code: 'kill 1234',
      options: ['SIGTERM (15)', 'SIGKILL (9)', 'SIGHUP (1)', 'SIGINT (2)'], answer: 0,
      explain: 'SIGTERM asks the process to shut down cleanly. SIGKILL (kill -9) forces it and should be a last resort.' },
    { level: 'mid', q: 'What does 2>&1 do here?', code: './backup.sh > backup.log 2>&1',
      options: ['Sends errors to the same place as normal output', 'Runs the script twice', 'Sends normal output to the error stream only', 'Discards all errors'], answer: 0,
      explain: 'File descriptor 2 (stderr) is redirected to wherever 1 (stdout) points, so both end up in backup.log.' },
    { level: 'mid', q: 'When does this cron job run?', code: '0 2 * * 1 /opt/scripts/report.sh',
      options: ['2:00 AM every Monday', '2:00 AM on the 1st of every month', 'Every 2 hours on Mondays', '1:02 AM every day'], answer: 0,
      explain: 'The fields are minute, hour, day of month, month and day of week. Day of week 1 is Monday.' },
    { level: 'mid', q: 'What does this pipeline produce?', code: "awk '{print $1}' access.log | sort | uniq -c | sort -rn | head",
      options: ['The 10 most frequent client IPs in the log', 'The first 10 lines of the log', 'Unique URLs in alphabetical order', 'The number of lines in the log'], answer: 0,
      explain: 'awk pulls the first field (the client IP in common log format), uniq -c counts each, sort -rn ranks by count and head shows the top 10.' },
    { level: 'mid', q: 'What does this do?', code: "sed -i 's/staging/production/g' app.conf",
      options: ['Replaces every "staging" with "production" in the file itself', 'Prints the file with replacements but leaves it unchanged', 'Replaces only the first match in the file', 'Deletes lines containing "staging"'], answer: 0,
      explain: '-i edits in place and g replaces every match on each line. Without -i, sed only prints the result.' },
    { level: 'mid', q: 'How do you add alice to the docker group without removing her other groups?',
      options: ['usermod -aG docker alice', 'usermod -G docker alice', 'useradd -G docker alice', 'groupadd alice docker'], answer: 0,
      explain: 'Without -a, usermod -G replaces all of alice\'s extra groups with just docker. A classic mistake.' },
    { level: 'mid', q: 'Which file on a server lists the public keys allowed to log in as a user over SSH?',
      options: ['~/.ssh/authorized_keys', '~/.ssh/known_hosts', '~/.ssh/id_rsa', '/etc/ssh/ssh_config'], answer: 0,
      explain: 'authorized_keys holds allowed public keys. known_hosts stores fingerprints of servers you have connected to.' },
    { level: 'mid', q: 'Which tool would you use to check what IP address a hostname resolves to?',
      options: ['dig example.com', 'route example.com', 'ifconfig -d example.com', 'arp example.com'], answer: 0,
      explain: 'dig queries DNS directly. nslookup and host work too.' },
    { level: 'mid', q: 'What does this do?', code: 'nohup ./long_job.sh &',
      options: ['Runs it in the background and keeps it running after you log out', 'Runs it with no output at all', 'Runs it at the lowest CPU priority', 'Schedules it for the next reboot'], answer: 0,
      explain: 'nohup ignores the hangup signal sent at logout, and & puts it in the background. Output goes to nohup.out by default.' },
    { level: 'mid', q: 'A 2-core server shows a load average of 8.00. What does that suggest?',
      options: ['Far more work is queued than the CPUs can handle', 'The server is using 8% of its CPU', 'Eight users are logged in', 'The server has been up for 8 days'], answer: 0,
      explain: 'Load counts processes running or waiting. On Linux it also includes tasks stuck waiting on disk I/O, so check both CPU and I/O.' },
    { level: 'mid', q: 'What does this command do?', code: 'chown -R www-data:www-data /var/www/site',
      options: ['Sets the owner and group of the folder and everything in it', 'Gives www-data read-only access', 'Changes permissions to 755 recursively', 'Copies the site to the www-data home folder'], answer: 0,
      explain: 'chown changes ownership, user:group sets both, and -R applies it recursively.' },

    // ---------- Senior ----------
    { level: 'senior', q: 'df shows / is 100% full, but du adds up to far less. What is the most likely cause?',
      options: ['A deleted file is still held open by a running process', 'The filesystem has run out of inodes', 'du ignores hidden files', 'The disk is failing'], answer: 0,
      explain: 'Space is not freed until the process closes the file. Find it with lsof +L1, then restart the process or truncate via /proc/PID/fd.' },
    { level: 'senior', q: 'Writes fail with "No space left on device" but df -h shows 40% free. What should you check?',
      options: ['Inode usage with df -i', 'Memory with free -h', 'Swap with swapon -s', 'Open ports with ss -tlnp'], answer: 0,
      explain: 'Millions of tiny files (session or cache files, mail queues) can use up every inode while plenty of bytes remain.' },
    { level: 'senior', q: 'A process shows state D in ps and ignores kill -9. What is happening?',
      options: ['It is in uninterruptible sleep, usually waiting on I/O', 'It is a zombie waiting to be reaped', 'It is being debugged', 'It is a daemon protected by systemd'], answer: 0,
      explain: 'D state processes cannot handle signals until the I/O returns. Common causes are a hung NFS mount or a failing disk.' },
    { level: 'senior', q: 'How do you get rid of a zombie process?',
      options: ['Signal or restart its parent process so it reaps the zombie', 'kill -9 the zombie\'s PID', 'Delete its folder in /proc', 'Zombies can only be cleared by rebooting'], answer: 0,
      explain: 'A zombie has already exited. It stays until its parent reads its exit status. If the parent dies, init adopts and reaps it.' },
    { level: 'senior', q: 'What does this line at the top of a bash script do?', code: 'set -euo pipefail',
      options: ['Exits on errors, errors on unset variables, and fails pipelines if any part fails', 'Enables debug output for every line', 'Makes the script run as root', 'Prevents the script from being run twice'], answer: 0,
      explain: 'This "strict mode" stops scripts from carrying on silently after something breaks. set -x is the one that prints each command.' },
    { level: 'senior', q: 'A Java process keeps disappearing with no error in its own logs. How do you check if the kernel killed it?',
      options: ['dmesg -T | grep -i "killed process"', 'free -h', 'cat /var/log/oom', 'top -o %MEM'], answer: 0,
      explain: 'The OOM killer logs to the kernel ring buffer. journalctl -k shows the same messages on systemd systems.' },
    { level: 'senior', q: 'On a RHEL system, which command tells you which package installed /usr/bin/curl?',
      options: ['rpm -qf /usr/bin/curl', 'rpm -ql /usr/bin/curl', 'yum owner /usr/bin/curl', 'dnf which curl'], answer: 0,
      explain: 'rpm -qf queries which package owns a file. rpm -ql lists files in a package. On Debian, use dpkg -S.' },
    { level: 'senior', q: 'What does the t at the end of these permissions mean?', code: 'drwxrwxrwt  /tmp',
      options: ['Users can only delete or rename their own files in it', 'Files are deleted on reboot', 'The directory is temporary and in memory', 'Files inherit the directory\'s group'], answer: 0,
      explain: 'That is the sticky bit. Everyone can write to /tmp, but only a file\'s owner (or root) can remove it.' },
    { level: 'senior', q: 'An app hangs with nothing in its logs. Which tool shows the system calls it is making right now?',
      options: ['strace -p <PID>', 'top -p <PID>', 'pstree <PID>', 'nice -p <PID>'], answer: 0,
      explain: 'strace attaches to a running process. You will often see it blocked on a read, a lock or a network connect.' },
    { level: 'senior', q: 'nginx gets "permission denied" reading a new web folder, even though permissions are 755 and ownership is correct. RHEL, enforcing mode. Likely cause?',
      options: ['The folder has the wrong SELinux context', 'The sticky bit is set', 'The umask is too strict', 'The ulimit is too low'], answer: 0,
      explain: 'Check with ls -Z. Fix it with semanage fcontext to set the right type, then restorecon -Rv to apply it.' },
    { level: 'senior', q: 'A systemd service logs "Too many open files". What is the right fix?',
      options: ['Raise LimitNOFILE in the service\'s unit file', 'Add more swap space', 'Add inodes with tune2fs', 'chmod 777 the data directory'], answer: 0,
      explain: 'Services use the limits in their unit file, not your shell\'s ulimit. Use systemctl edit, then daemon-reload and restart.' },
    { level: 'senior', q: 'You delete a file that has both a hard link and a symbolic link pointing to it. What happens?',
      options: ['The hard link still works, the symlink is now broken', 'Both links still work', 'Both links break', 'The symlink still works, the hard link breaks'], answer: 0,
      explain: 'A hard link is another name for the same data, which survives until the last link goes. A symlink just points at a path.' },
    { level: 'senior', q: 'A server is slow and top shows a high "wa" value. What does that mean?',
      options: ['CPUs are idle while waiting for disk or other I/O', 'Too many users are waiting to log in', 'Processes are waiting for memory to be swapped in from the network', 'The CPU is overheating and throttling'], answer: 0,
      explain: 'High iowait points at storage. Dig in with iostat -x to find the busy device and iotop to find the process.' },
    { level: 'senior', q: 'What does this command do?', code: 'ssh -L 8080:db.internal:5432 admin@bastion',
      options: ['Forwards your local port 8080 through bastion to db.internal port 5432', 'Opens port 8080 on db.internal to the internet', 'Copies the database to port 8080 on bastion', 'Forwards bastion\'s port 5432 back to your machine on 8080 for everyone'], answer: 0,
      explain: 'Local forwarding lets you connect to localhost:8080 and reach a database you cannot access directly. -R does the reverse.' },
    { level: 'senior', q: 'Something changed in /etc in the last 24 hours. Which command finds the modified files?',
      options: ['find /etc -type f -mtime -1', 'find /etc -type f -mtime +1', 'find /etc -type f -atime 1', 'find /etc -newer 24h'], answer: 0,
      explain: '-mtime -1 means modified less than one day ago. +1 means more than one day ago.' },
    { level: 'senior', q: 'How do you make a kernel setting like vm.swappiness survive a reboot?',
      options: ['Add it to a file in /etc/sysctl.d/ and run sysctl --system', 'Run sysctl -w vm.swappiness=10', 'Write the value to /proc/sys/vm/swappiness', 'Add it to root\'s ~/.bashrc'], answer: 0,
      explain: 'sysctl -w and writing to /proc only change the running kernel. Files in /etc/sysctl.d/ are applied at every boot.' }
  ]
};
